### ISSUE TITLE
Implement converting items to expandable list

### ISSUE THREAD

**Issue by LiubovSmorhonska** [Correlate-AS/customer-insights#10]

**Comment by LiubovSmorhonska** [comment]
@olegoethe we already have this logic, but not in the item menu.
To convert the item, for example, bullet list to expandable list, you need:
1. Set the cursor before item text
2. Push backspace (remove bullet sign)
3. Type the right arrow ">" and press space button 

By the way it would be good to explain this to users.
Do we need to show it in menu?

**Comment by olegoethe** [comment]
Ideally we should be able to have a smart converter in the item menu. Possible?

**Comment by LiubovSmorhonska** [comment]
@olegoethe Yes, it could be like this:
We can change menu a little. We will have "convert to" in menu and little right arrow. Then you click on it and you get new level of menu with options: bullet, to-do, numbered, expandable list. Also we could add some icons for nice UI. What do you think?

**Comment by olegoethe** [comment]
Can you please make a mockup in Figma? @LiubovSmorhonska

**Comment by LiubovSmorhonska** [comment]
@olegoethe check please
https://www.figma.com/file/ftuzXl4F0mq9m2Alp16e58/Chat?node-id=0%3A1
