### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by olegoethe** [Correlate-AS/customer-insights#11]
https://user-images.githubusercontent.com/29142826/138678114-455f2b21-8adc-4f4b-83fc-07600514ebaa.mp4

<img width="1792" alt="Skjermbilde 2021-10-22 kl  19 35 33" src="https://user-images.githubusercontent.com/29142826/138678281-3b4b85e4-cfd1-4d01-8ad7-fd1f844cd6ea.png">
<img width="1792" alt="Skjermbilde 2021-10-22 kl  19 35 31" src="https://user-images.githubusercontent.com/29142826/138678287-7a09022d-1b4e-4ca5-93e5-3afec300e087.png">
<img width="1792" alt="Skjermbilde 2021-10-22 kl  19 35 28" src="https://user-images.githubusercontent.com/29142826/138678293-5f948221-fc13-4917-9e84-742427d97181.png">

**Comment by LiubovSmorhonska** [comment]
Hi @olegoethe ! We are working on fixing bugs connected with collaborative work right now. That is why could be a lot of errors.

**Comment by olegoethe** [comment]
Ok, great. Thanks!

**Comment by LiubovSmorhonska** [comment]
fixed in https://github.com/Correlate-AS/frontend/issues/3793
