### ISSUE TITLE
Be able to see email address when receiving request to join a team

### ISSUE THREAD

**Issue by jedelizabella** [Correlate-AS/customer-insights#13]
Problem: when receiving a request to join a team the user has to go to members to see the email address of the person who want to join the board.

![Screenshot 2021-10-25 at 13 10 54](https://user-images.githubusercontent.com/89971706/138707128-787def15-5ba2-4a13-a06e-e699fca763ed.png)
<img width="850" alt="Screenshot 2021-10-25 at 15 45 28" src="https://user-images.githubusercontent.com/89971706/138707207-1c46efe4-8a72-4261-990e-841b1705ca80.png">

Solution: let users see the email address of the user that want to join the team directly in the email.

**Comment by voznyigor** [comment]
@olegoethe can we have your approval for this task?

**Comment by olegoethe** [comment]
Yes, approved.
