### ISSUE TITLE
Not able to move a board in the bottom right of the screen

### ISSUE THREAD

**Issue by jedelizabella** [Correlate-AS/customer-insights#19]
Problem: When I have two rows with boards, I cannot move the board to the bottom right since the the chat box is in the way. 
<img width="1215" alt="Screenshot 2021-10-26 at 09 35 22" src="https://user-images.githubusercontent.com/89971706/138840294-bee9836e-8123-43fc-ad06-07170bfa6004.png">

Solution: include more space between the last row of boards and the chatbox to be able to press "Move".

**Comment by olegoethe** [comment]
Make sense :)
