### ISSUE TITLE
Create list with items inside

### ISSUE THREAD

**Issue by jedelizabella** [Correlate-AS/customer-insights#23]
Problem: when I create a list item the rest of the list items convert to one in case I add items in between.
https://user-images.githubusercontent.com/89971706/139025281-b3c69703-c05c-4e6c-9d8f-738ee6d2de12.mov

Suggested solution: Keep remaining numbers the same even if items are added in between. This is how it works in Google Docs for example: 

https://user-images.githubusercontent.com/89971706/139025395-9b4751e4-6a68-4301-b9e1-54a657d6e286.mov

**Comment by olegoethe** [comment]
Good point!. 

Ref previous ticket comment.
