### ISSUE TITLE
Moving boards from team to private board duplicates the board 3 times

### ISSUE THREAD

**Issue by jedelizabella** [Correlate-AS/customer-insights#27]
Issue: when I move a board from a team to my private boards the boards duplicates so that I have 3 of the same board in my private boards. In the screenshot below I moved the boards Meetings and Data Management Plan from a team to my private boards and as you can see there are now 3 of each board instead of one. 
![Screenshot 2021-11-22 at 10 43 04](https://user-images.githubusercontent.com/89971706/142838568-1b0f3c60-257e-4405-aaed-b97254c2d39c.png)

Steps to reproduce: Move board from team to "No team by default - goes into personal boards", when you go into personal boards you now see three of the same board.

**Comment by LiubovSmorhonska** [comment]
@jedelizabella I tried to reproduce and got 2 duplicates. Then I refreshed the page and saw one board, without copies. Can you try to refresh and let me know? It must be problem with cache memory and will be fixed :)

**Comment by jedelizabella** [comment]
Thank you Liubov. When I refresh the browser there is only one board as it should be :)
