### ISSUE TITLE
keep me signed in

### ISSUE THREAD

**Issue by PriscilaSelmo** [Correlate-AS/customer-insights#5]
Hi, 

I was wondering if there's a way we can allow the user to chose the option "keep me signed in" or "remember me".

Right now I have to login to the platform every single time, even if I'm using the same browser! 
Thinking about the experience, that would be great if we could have the platform logging in automatically, especially if we think about the mobile version/app. 

Let me know what you think :)

**Comment by ghost** [comment]
Good idea. I haven't found it that big of a pain point (on desktop Chrome) personally - cuz it "remembers" me/my password when I simply click 'sign in w/ Google'. If I had to type this all out every log in, I would get annoyed. I can see it being a bigger issue on mobile.
